### ISSUE TITLE
consider `Borrow<str>`

### ISSUE THREAD

**Issue by ickk** [drash-course/interned-string#1]
Hi, really nice crate you've got! I also just happened to publish a similar crate of mine ([`sinter`](https://github.com/ickk/sinter)) at almost the exact same time as you, I thought we may be able to share ideas :)

I notice you already impl `AsRef<str>`, it's cousin [`Borrow<str>`](https://doc.rust-lang.org/1.79.0/core/borrow/trait.Borrow.html) is something I've found useful when prototyping and may be worth consideration in this crate (be mindful of its relationship to `Hash` & `Eq`, an unfortunate trade-off is that Hash must defer to the `str`'s Hash).

**Comment by drash-course** [comment]
Hi, thanks for the suggestion. I've read about `Borrow<str>` yesterday but chose to not implement it because of the following remark :

> In particular Eq, Ord and Hash must be equivalent for borrowed and owned values: x.borrow() == y.borrow() should give the same result as x == y.

In my case, `Hash` is implemented by hashing the `IString`'s key. This is desirable because it's the fastest / cheapest option, and fast hashing may be the reason you would intern strings in the first place. Unfortunately this means that the hash of an `IString` is not comparable with the hash of a `&str` or `String`.

If my reading of `Borrow` is correct, this precludes `IString` from implementing `Borrow<str>`.

`IString` implements `AsRef` and `Deref` so I figured that not implementing `Borrow` wouldn't be too much of an issue. If you need it, you can wrap `IString` in your own type and re-implement `Hash` to make it compliant.

**Comment by drash-course** [comment]
Your crate looks very interesting, I like the way you do lockless reading.

> When a thread wants to inspect the "readable table" they increment an atomic counter. They increment this counter again when they are done reading. This allows the writer to reliably wait on lingering reads after the atomic table swap.

This is basically how `left-right` does synchronisation as well.

How do you free interned strings that are no longer used? I don't see a `Drop` impl for `IStr`.

**Comment by ickk** [comment]
> This is basically how `left-right` does synchronisation as well.

I think I listened to Jon Gjengset talk about noria a long time ago, and this may well have been where I got the idea from

> How do you free interned strings that are no longer used? I don't see a `Drop` impl for `IStr`.

I don't - In `sinter` the strings backing `IStr`s just become `'static` (live until the end of the program). This is something I have thought about, there's a solution using an atomic counter per entry; I'd have to give up `Copy` and the ability to get the `&'static str`. - However in my particular use-case for interning strings, the memory usage is not a concern I have so I haven't done this yet

**Comment by ickk** [comment]
> In my case, `Hash` is implemented by hashing the `IString`'s key. This is desirable because it's the fastest / cheapest option, and fast hashing may be the reason you would intern strings in the first place

yeah this is a consideration I went back and forth on. Some of the reasoning for my choice in the end was that where the hashing speed matters, I could be using a specialised datastructure where I can provide my own hash; e.g. hashbrown's HashTable, and I could use the id itself (nohash) or a cached value (I happen to store a hash next to my string contents in memory)
